# Generated by Django 5.0.7 on 2024-08-04 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'verbose_name': 'Позиция меню', 'verbose_name_plural': 'Позиции меню'},
        ),
    ]
